### ISSUE TITLE
Polish CausalFrames API

### ISSUE THREAD

**Issue by MaximilianFranz** [inovex/justcause#3]
A few questions: 

* When calling `df.np.X`, we get all covariates for all replications. Should we be returning the covariates for a specific replication instead? After all, this is what users expect in order to pass it to methods. 

* Alternatively, add a `get_replication` method on which we can then call the NumPy accessor  `.np.X`

* Can we carry more information in the `names` accessor? E.g. `num_replications`, `num_instances`, ...

**Comment by FlorianWilhelm** [comment]
Since the methods/learners operate only on a single operation it makes sense to rather provide an iterator of dataframes that each correspond to a single replication instead of a dataframe encompassing multiple replications. Thus we could drop Scikit-Learn's data bunches and use iterators instead. Following this approach would render special methods for dataframes in order to deal with replication useful and thus make the API simpler and more concise. This approach is implemented currently on the `causal_frames` branch.

**Comment by FlorianWilhelm** [comment]
This is done and merged into master.
